---
- name: Initialize Kubernetes cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address [master-ip]

- name: Create .kube directory
  become: yes
  become_user: "{{ ansible_user }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to User's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
